spring.datasource.url: jdbc:mysql://localhost:3306/skillbox?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL
  =false
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: update

spring.mail.username: email@gmail.com
spring.mail.password: password
spring.mail.port: 587
spring.mail.protocol: smtp
spring.mail.test-connection: true
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.transport.protocol: smtp
spring.mail.properties.mail.debug: false
spring.mail.host: smtp.gmail.com