spring.datasource.url: jdbc:mysql://93.186.255.195:3306/dip_zbor?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL
  =false
spring.datasource.username: dip_zbor
spring.datasource.password: DCRB9zzhH99WkXqX
spring.jpa.properties.hibernate.default_schema: dip_zbor
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true

spring.mail.username: email@gmail.com
spring.mail.password: password
spring.mail.port: 587
spring.mail.protocol: smtp
spring.mail.test-connection: true
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.transport.protocol: smtp
spring.mail.properties.mail.debug: false
spring.mail.host: smtp.gmail.com
spring.image.reference: /src/main/resources/images/upload/