spring.datasource.url: jdbc:mysql://localhost:3306/skillbox?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: update